noverde/faster-sam

CONTRIBUTING.md

feat: add contrubuting file

---

pyproject.toml

feat: update toml file

---

README.md

refactor: update readme file

---

faster_sam/adapter.py

* Add adapter module documentation using docstrings
[Task 149630](https://dotzmkt.visualstudio.com/Arquitetura/_workitems/edit/149630): Criar documentação dos modulos

docs: add adapter module documentation using docstrings

---

faster_sam/cloudformation.py

* Add cloudformation module documentation
[Task 149630](https://dotzmkt.visualstudio.com/Arquitetura/_workitems/edit/149630): Criar documentação dos modulos

docs: add cloudformation module documentation

---

faster_sam/routing.py

* Add routing  module documentation

docs: add routing  module documentation

---

faster_sam/routing.py

* Update routing module documentation

docs: update routing module documentation 

---

docs/faster_sam.adapter.rst
docs/faster_sam.cloudformation.rst
docs/faster_sam.middleware.rst
docs/faster_sam.openapi.rst
docs/faster_sam.routing.rst
docs/faster_sam.rst

* Add initial documentation configure files

feat: add initial documentation configure files

---

docs/conf.py
pyproject.toml

chore: bump version from 0.1.0 to 0.2.0

---

faster_sam/adapter.py
faster_sam/cloudformation.py
faster_sam/middleware.py

* Update class parameters of docstrings

refactor: update class parameters of docstrings

---

pyproject.toml

* Update fastapi dependency to any version

chore: update fastapi dependency to any version

---

pyproject.toml

feat: new project version

---

Makefile

* Buffer stdout and stderr during tests

chore: Buffer stdout and stderr during tests

---

pyproject.toml

chore: bump version to 0.4.0

---

faster_sam/routing.py
tests/test_routing.py

* Add authorization data in context request

feat: add authorizer in context

---

pyproject.toml

chore: bump version to 0.5.0

---

pyproject.toml

chore: bump version to 0.5.1

---

tests/test_middleware_lambda_authorizer.py

feat: improve tests credentials

---

pyproject.toml

chore: bump version to 0.6.0

---

docs/faster_sam.adapter.rst
docs/faster_sam.cache.rst
docs/faster_sam.cloudformation.rst
docs/faster_sam.middleware.rst
docs/faster_sam.middlewares.rst
docs/faster_sam.openapi.rst
docs/faster_sam.routing.rst
docs/faster_sam.rst
docs/index.rst
docs/modules.rst

docs: update docs modules

---

docs/conf.py
pyproject.toml

* Bump faster-sam from 0.6.0 to 0.7.0
[Task 151823](https://dotzmkt.visualstudio.com/Arquitetura/_workitems/edit/151823): Lançar release do Faster-sam

chore: bump faster-sam from 0.6.0 to 0.7.0

---

faster_sam/adapter.py
tests/fixtures/templates/example6.yml

* Check iif resource arn is a list

fix: check if resource arn is a list

---

docs/conf.py
pyproject.toml

* Bump faster-sam from 0.7.0 to 0.7.1

chore: bump faster-sam from 0.7.0 to 0.7.1

---

faster_sam/lambda_event.py
faster_sam/middlewares/rewrite_path.py
faster_sam/routing.py

* Fix problem consuming body in middleware, its a know problemn in versions of fastapi before december/23
* Add logs

fix: remove set body middleware

---

pyproject.toml

- [] Bugfix
* Bump version to 0.9.0

chore: bump version to 0.9.0

---

faster_sam/lambda_event.py
tests/test_routing.py

* Update schedule functions to use background tasks

feat: use background tasks

---

pyproject.toml

- [] Bugfix
* Bump version to 0.10.0

Chore/bump verion to 0.10.0

---

.gitignore
faster_sam/cloudformation.py
tests/fixtures/templates/example2.yml
tests/fixtures/templates/example3.yml
tests/test_cloudformation.py

* Add set parameters function into cloudformation

feat: add set parameters function into cloudformation

---

faster_sam/adapter.py
tests/test_adapter.py

feat: load envs into adapter

---

faster_sam/adapter.py
faster_sam/cloudformation.py

fix: convert to string

---

docs/conf.py
pyproject.toml

* Bump faster-sam 0.10.0 to 0.11.0

chore: bump faster-sam 0.10.0 to 0.11.0

---

faster_sam/adapter.py
faster_sam/cloudformation.py

refactor: add env value casting

---

faster_sam/cloudformation.py
tests/test_cloudformation.py

* Add AWS CloudFormations resource class for Lambda Function

feat: add aws resource class definition for Lambda Function

---

faster_sam/cloudformation.py
tests/test_cloudformation.py

feat: add bucket class

---

faster_sam/adapter.py
faster_sam/cloudformation.py

* Update EventType value name for `Schedule`.

fix: event source enum value name

---

faster_sam/adapter.py
faster_sam/cloudformation.py
tests/test_cloudformation.py

feat: add aws api gateway class

---

faster_sam/cloudformation.py
tests/test_cloudformation.py

* Add AWS CloudFormation event source class definition for Schedule.

feat: add aws event source class definition for schedule

---

faster_sam/cloudformation.py

* Update EventSource class method `from_resource` improving the event source type mapping returning a more specialized instance class when possible.

feat: improve event source creating from resource map

---

faster_sam/adapter.py
faster_sam/cloudformation.py
faster_sam/cmd/faster.py
tests/test_cloudformation.py

* Update CloudFormation property `functions` returning a dictionary of instances instead of pure dictionaries.

feat: return instance of function instead of dictionary on cf propety

---

faster_sam/cloudformation.py
faster_sam/cmd/faster.py
tests/test_cloudformation.py

* Update CloudFormation property buckets returning a dictionary of instances instead of pure dictionaries.

feat: return instance of buckets instead of dictionary on cf propety

---

faster_sam/adapter.py
tests/fixtures/templates/example5.yml
tests/fixtures/templates/swagger_private.yml
tests/test_adapter.py

* Update Adapter lambda mapper function.
* Update unit tests and fixtures.

refactor: adapter lambda-mapper function

---

faster_sam/adapter.py
tests/fixtures/templates/example6.yml

* Add support for mapping Lambda Functions SQS events.
* Remove lambda_queue_mapper funcion.
* Update fixture.

refactor: update lambda-mapper function

---

faster_sam/adapter.py

* Update lambda_mapper function to map schedule events.
* Remove lambda_scheduel_mapper function.

refactor: update lambda-mapper to process schedule events

---

faster_sam/adapter.py
faster_sam/cloudformation.py
tests/test_cloudformation.py

* Remove lambda handler function

feat: remove lambda handler function

---

faster_sam/adapter.py
faster_sam/cloudformation.py
tests/test_cloudformation.py

feat: add s3 event

---

faster_sam/middlewares/lambda_authorizer.py
tests/test_middleware_lambda_authorizer.py

* Refactor Lambda authorizer middleware to asgi format

refactor: change authorizer middleware to asgi

---

docs/conf.py
pyproject.toml

* Bump version 0.11.0 to 0.11.1

chore: bump version 0.11.0 to 0.11.1

---

faster_sam/lambda_event.py

* Add authorizer scope to lambda event.

feat: add authorizer scope

---

pyproject.toml

* Update package version to 0.12.0.

chore: bump version 0.12.0

---

docs/conf.py
pyproject.toml

* bump faster-sam version 0.12.0 to 0.12.1

chore: bump faster-sam version 0.12.0 to 0.12.1 

---

requirements-dev.txt

* Add httpx into dev requirements

fix: add httpx into dev requirements 

---

faster_sam/dependencies/events.py
faster_sam/protocols.py
faster_sam/schemas.py
tests/test_dependencies_events.py

feat: add sqs event builder (#2)

---

docs/conf.py
pyproject.toml

chore: bump version
